List<String> khodam = [
  'kosong',
  'macan sunda',
  'kucing terbang',
  'macan pemarah',
  'beruang sunda',
  'kaleng kejepit',
  'panci gosong',
  'aspal putih',
  'harimau birahi',
  'burung berenang',
  'kanebo kering',
  'kapal keram',
  'nyi blorong',
  'rawa rontok',
  'kasur empuk',
  'bantal kapas',
  'kulkas gosong',
  'payung robek',
  'topi runcing',
  'gunting tumpul',
  'jam dandang',
  'senter mati',
  'kerupuk garing',
  'penggaris bengkok',
  'kancut badak',
  'tali jemuran',
  'pagar besi',
  'kunci gembok',
  'cupang mancung',
  'sundel bolong',
  'tuyul gondrong',
  'tuyul kesandung',
  'cicak kawin',
  'genderuwo tiktok',
  'susu kental manis',
  'semut hijau',
  'pocong ngesot',
  'tuyul selfie',
  'senar gitar',
  'handuk basah',
  'kuntilanak part time',
  'tisu gulung',
  'gelas plastik',
  'donat kering',
  'kentang ting tung',
  'kuntilanak pake kacamata',
  'keripik pedas',
  'genderuwo kolektor komik',
  'jin nge gym',
  'pizza keju',
  'coklat batangan',
  'kuntilanak makeup',
  'tuyul kuliah',
  'sendal jepit',
  'kaos oblong',
  'kipas angin',
  'pocong joget',
  'kuntilanak karaoke',
  'buku kusut',
  'lemari penuh'
];
